name: EnderChestExpansion
version: 1.0
main: net.nomindev.EnderChestExpansion
api-version: 1.20
depend: [Vault]
commands:
  ec:
    description: Open your Ender Chest expansion GUI
    usage: /<command>
    aliases: [enderchest]
  enderchestexpansion:
    description: Main command for EnderChestExpansion
    usage: /<command>
permissions:
  enderchestexpansion.use:
    description: Allows players to use the EnderChestExpansion plugin
    default: true
  enderchestexpansion.admin:
    description: Gives access to admin commands
    default: op